config/routes.rb
WebStudy::Application.routes.draw do
  resources :contacts do as_routes end

  resources :purecsses

  resources :customers

  get "simplenav/show"

  get "poptab/show"

  get "navigationbar/index"

  resources :lessons

  get "customers/index"

  get "csstableblue/index"

  get "googlenowcard/index"

  get "purecsses/index"

  root :to => "lessons#index"

end

app/models/atable.rb
class Atable < ActiveRecord::Base
  attr_accessible :name
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :mobile, :name, :remark, :telephone, :title
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :adress, :email, :name, :phone
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :description, :image_url, :level, :title
end

app/models/purecss.rb
class Purecss < ActiveRecord::Base
  attr_accessible :element
end

app/controllers/atables_controller.rb
class AtablesController < ApplicationController
  active_scaffold :"atable" do |conf|
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  active_scaffold :"contact" do |conf|
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @customer  = Customer.new

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js { render action: "new" }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js{ render action: "edit"}
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.js
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/poptab_controller.rb
class PoptabController < ApplicationController
  def show
  end
end

app/controllers/purecsses_controller.rb
class PurecssesController < ApplicationController
  # GET /purecsses
  # GET /purecsses.json
  def index
    @purecsses = Purecss.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purecsses }
    end
  end

  # GET /purecsses/1
  # GET /purecsses/1.json
  def show
    @purecss = Purecss.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purecss }
    end
  end

  # GET /purecsses/new
  # GET /purecsses/new.json
  def new
    @purecss = Purecss.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purecss }
    end
  end

  # GET /purecsses/1/edit
  def edit
    @purecss = Purecss.find(params[:id])
  end

  # POST /purecsses
  # POST /purecsses.json
  def create
    @purecss = Purecss.new(params[:purecss])

    respond_to do |format|
      if @purecss.save
        format.html { redirect_to @purecss, notice: 'Purecss was successfully created.' }
        format.json { render json: @purecss, status: :created, location: @purecss }
      else
        format.html { render action: "new" }
        format.json { render json: @purecss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purecsses/1
  # PUT /purecsses/1.json
  def update
    @purecss = Purecss.find(params[:id])

    respond_to do |format|
      if @purecss.update_attributes(params[:purecss])
        format.html { redirect_to @purecss, notice: 'Purecss was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purecss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purecsses/1
  # DELETE /purecsses/1.json
  def destroy
    @purecss = Purecss.find(params[:id])
    @purecss.destroy

    respond_to do |format|
      format.html { redirect_to purecsses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atables_helper.rb
module AtablesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/csstableblue_helper.rb
module CsstableblueHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/googlenowcard_helper.rb
module GooglenowcardHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/navigationbar_helper.rb
module NavigationbarHelper
end

app/helpers/poptab_helper.rb
module PoptabHelper
end

app/helpers/purecsses_helper.rb
module PurecssesHelper
end

app/helpers/simplenav_helper.rb
module SimplenavHelper
end

app/views/poptab/show.html.erb
<h1>Poptab#show</h1>
<p>Find me in app/views/poptab/show.html.erb</p>

<a href="#openModal">Open Modal</a>
<div id="openModal" class="modalDialog">
	<div>
		<a href="#close" title="Close" class="close"> X </a>
		<h3>Select Your Customer Order</h3>
		<p> This is sample modal dialog, I want use it as database search</p>
		<hr class="gray">
		
		<div class="tablearea">
		<table>
		  <tr class='list_line_odd'>
		    <th>Name</th>
		    <th>Code</th>
		    <th>Contact</th>
		    <th>Level</th>
		  </tr>

		<% 1.upto(5) %>
		<% 1.upto(5) do |i| %>
		  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
		    <td>Name <%= i.to_s %></td>
		    <td>Code <%= i.to_s %></td>
		    <td>Contact <%= i.to_s %></td>
		    <td>Level <%= i.to_s %></td>
		  </tr>
		<% end %>
		</table>
	</div>
	</div>
</div>

app/views/purecsses/_form.html.erb
<%= form_for(@purecss) do |f| %>
  <% if @purecss.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purecss.errors.count, "error") %> prohibited this purecss from being saved:</h2>

      <ul>
      <% @purecss.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :element %><br />
    <%= f.text_field :element %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purecsses/edit.html.erb
<h1>Editing purecss</h1>

<%= render 'form' %>

<%= link_to 'Show', @purecss %> |
<%= link_to 'Back', purecsses_path %>

app/views/purecsses/index.html.erb
<div id = "layout-container">
  <div id = "menu">
    <ul>
      <li class="nav_left"><a href="#">Home    </a></li>
      <li class="nav_left"><a href="#">Group#Sales</a></li>
      <li class="nav_right"><a href="#">@Qinkunsong</a></li>
      <li class="nav_right"><a href="#">Product </a></li>
      <li class="nav_right"><a href="#">Customer</a></li>
      <li class="nav_right"><a href="#">Supplier</a></li>
    </ul>
  </div>
  <div id = "layout-content-container">
    <div id = "layout-aside">
      <div class="pure-menu pure-menu-open">
          <a class="pure-menu-heading">HOME</a>

          <ul>
              <li><a href="#">Customer Order</a></li>
              <li><a href="#">Sales Order</a></li>
              <li><a href="#">Wiki</a></li>
              <li><a href="#">Finance</a></li>
              <li class="pure-menu-heading">Tools</li>
              <li><a href="#">Prices</a></li>
              <li><a href="#">Report</a></li>
              <li><a href="#">OMG!</a></li>
          </ul>
      </div>
    </div>

    <div id = "layout-content">
      <h1>Simplenav#show</h1>
      <p>Find me in app/views/simplenav/show.html.erb</p>
      <p>http://www.maxdesign.com.au/articles/css-layouts/two-liquid/</p>

      <h1>Listing purecsses</h1>

      <table class="pure-table pure-table-bordered">
        <thead>
        <tr>
          <th>Element</th>
          <th>show</th>
          <th>Edit</th>
          <th>Del</th>
        </tr>
      </thead>

      <tbody>
      <% @purecsses.each do |purecss| %>
        <tr>
          <td><%= purecss.element %></td>
          <td><%= link_to 'Show', purecss %></td>
          <td><%= link_to 'Edit', edit_purecss_path(purecss) %></td>
          <td><%= link_to 'Destroy', purecss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
      </table>

      <br />

      <%= link_to 'New Purecss', new_purecss_path %>

      <h1>Forms</h1>
      <form class="pure-form">
        <fieldset>
            <legend>A compact inline form</legend>

            <input type="email" placeholder="Email">
            <input type="password" placeholder="Password">

            <label for="remember">
                <input id="remember" type="checkbox"> Remember me
            </label>

            <button type="submit" class="pure-button pure-button-primary">Sign in</button>
        </fieldset>
      </form>

      <form class="pure-form pure-form-stacked">
        <fieldset>
          <legend>A Stacked Form</legend>

          <label for="email">Email</label>
          <input id="email" type="email" placeholder="Email">

          <label for="password">Password</label>
          <input id="password" type="password" placeholder="Password">

          <label for="state">State</label>
          <select id="state">
            <option>AL</option>
            <option>CA</option>
            <option>IL</option>
          </select>

          <label for="remember" class="pure-checkbox">
              <input id="remember" type="checkbox"> Remember me
          </label>

          <button type="submit" class="pure-button pure-button-primary">Sign in</button>
        </fieldset>
      </form>

      <form class="pure-form pure-form-aligned">
          <fieldset>
              <div class="pure-control-group">
                  <label for="name">Username</label>
                  <input id="name" type="text" placeholder="Username">
              </div>

              <div class="pure-control-group">
                  <label for="password">Password</label>
                  <input id="password" type="password" placeholder="Password">
              </div>

              <div class="pure-control-group">
                  <label for="email">Email Address</label>
                  <input id="email" type="email" placeholder="Email Address">
              </div>

              <div class="pure-control-group">
                  <label for="foo">Supercalifragilistic Label</label>
                  <input id="foo" type="text" placeholder="Enter something here...">
              </div>

              <div class="pure-controls">
                  <label for="cb" class="pure-checkbox">
                      <input id="cb" type="checkbox"> I've read the terms and conditions
                  </label>

                  <button type="submit" class="pure-button pure-button-primary">Submit</button>
              </div>
          </fieldset>
      </form>

      <h1> Buttons </h1>
      <a class="pure-button pure-button-disabled" href="#">A Disabled Button</a>
      <button class="pure-button pure-button-disabled">A Disabled Button</button>

      <a class="pure-button pure-button-active" href="#">An Active Button</a>
      <button class="pure-button pure-button-active">An Active Button</button>

      <a class="pure-button pure-button-primary" href="#">A Primary Button</a>
      <button class="pure-button pure-button-primary">A Primary Button</button>

      <h1>pages</h1>  

    </div>
</div>

app/views/purecsses/new.html.erb
<h1>New purecss</h1>

<%= render 'form' %>

<%= link_to 'Back', purecsses_path %>

app/views/purecsses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Element:</b>
  <%= @purecss.element %>
</p>


<%= link_to 'Edit', edit_purecss_path(@purecss) %> |
<%= link_to 'Back', purecsses_path %>