config/routes.rb
WebStudy::Application.routes.draw do
  resources :contacts do as_routes end

  resources :purecsses

  resources :customers

  get "simplenav/show"

  get "poptab/show"

  get "navigationbar/index"

  resources :lessons

  get "customers/index"

  get "csstableblue/index"

  get "googlenowcard/index"

  get "purecsses/index"

  root :to => "lessons#index"

end

app/models/atable.rb
class Atable < ActiveRecord::Base
  attr_accessible :name
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :mobile, :name, :remark, :telephone, :title
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :adress, :email, :name, :phone
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  attr_accessible :description, :image_url, :level, :title
end

app/models/purecss.rb
class Purecss < ActiveRecord::Base
  attr_accessible :element
end

app/controllers/atables_controller.rb
class AtablesController < ApplicationController
  active_scaffold :"atable" do |conf|
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  active_scaffold :"contact" do |conf|
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    @customer  = Customer.new

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.js
      else
        format.html { render action: "new" }
        format.js { render action: "new" }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.js
      else
        format.html { render action: "edit" }
        format.js{ render action: "edit"}
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.js
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.json
  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.html # new.html.erb
      format.js
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lessons/1
  # PUT /lessons/1.json
  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/poptab_controller.rb
class PoptabController < ApplicationController
  def show
  end
end

app/controllers/purecsses_controller.rb
class PurecssesController < ApplicationController
  # GET /purecsses
  # GET /purecsses.json
  def index
    @purecsses = Purecss.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @purecsses }
    end
  end

  # GET /purecsses/1
  # GET /purecsses/1.json
  def show
    @purecss = Purecss.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @purecss }
    end
  end

  # GET /purecsses/new
  # GET /purecsses/new.json
  def new
    @purecss = Purecss.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @purecss }
    end
  end

  # GET /purecsses/1/edit
  def edit
    @purecss = Purecss.find(params[:id])
  end

  # POST /purecsses
  # POST /purecsses.json
  def create
    @purecss = Purecss.new(params[:purecss])

    respond_to do |format|
      if @purecss.save
        format.html { redirect_to @purecss, notice: 'Purecss was successfully created.' }
        format.json { render json: @purecss, status: :created, location: @purecss }
      else
        format.html { render action: "new" }
        format.json { render json: @purecss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /purecsses/1
  # PUT /purecsses/1.json
  def update
    @purecss = Purecss.find(params[:id])

    respond_to do |format|
      if @purecss.update_attributes(params[:purecss])
        format.html { redirect_to @purecss, notice: 'Purecss was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @purecss.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purecsses/1
  # DELETE /purecsses/1.json
  def destroy
    @purecss = Purecss.find(params[:id])
    @purecss.destroy

    respond_to do |format|
      format.html { redirect_to purecsses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/simplenav_controller.rb
class SimplenavController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atables_helper.rb
module AtablesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/csstableblue_helper.rb
module CsstableblueHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/googlenowcard_helper.rb
module GooglenowcardHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/navigationbar_helper.rb
module NavigationbarHelper
end

app/helpers/poptab_helper.rb
module PoptabHelper
end

app/helpers/purecsses_helper.rb
module PurecssesHelper
end

app/helpers/simplenav_helper.rb
module SimplenavHelper
end

app/views/customers/_card.html.erb
<p id="notice"><%= notice %></p>

<h3> Customers </h3>
<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Adress:</b>
  <%= @customer.adress %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<%= render "form" %>


app/views/customers/_customer.html.erb
  <tr>
    <td><%= customer.name %></td>
    <td><%= customer.adress %></td>
    <td><%= customer.phone %></td>
    <td><%= customer.email %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer), :remote => true %></td>
    <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>
  </tr>

app/views/customers/_edit_area.html.erb

<table>
<tr>
  <%= form_for(@customer, :remote => true) do |f| %>
    <td>
      <div class="td_field">
        <%= f.text_field :name %>
      </div>
    </td>
    <td>
      <div class="td_field">
        <%= f.text_area :adress %>
      </div>
    </td>
    <td>
      <div class="td_field">
        <%= f.text_field :phone %>
      </div>
    </td>
    <td>
      <div class="td_field">
        <%= f.text_field :email %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </td>
  <% end %>
</tr>
</table>

app/views/customers/_form.html.erb
<%= form_for(@customer, :remote => true) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :adress %><br />
    <%= f.text_area :adress %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/_show.html.erb
<h3> Customers show card</h3>
<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Adress:</b>
  <%= @customer.adress %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

app/views/customers/create.js.erb
$('<%= j(render(:partial => @customer)) %>').appendTo('#customers').fadeIn();
$("#new_customer")[0].reset();

app/views/customers/destroy.js.erb
$("#<%= dom_id @customer %>").remove();

app/views/customers/edit.js.erb
$("#customer_card").html("<%= j render "form" %>");

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table id="customers">
  <tr>
    <th>Name</th>
    <th>Adress</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.name %></td>
    <td><%= customer.adress %></td>
    <td><%= customer.phone %></td>
    <td><%= customer.email %></td>
    <td><%= link_to 'Show', customer, :remote => true %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer), :remote => true %></td>
    <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>


</table>

<br />
<!--
<h2> Customer form</h2>
<div id="form"> <%= render "form" %> </div>

<%= link_to 'Back', customers_path %>
-->

<%= link_to 'New Customer', new_customer_path, :remote => true %>

<div id="customer_card">

</div>

app/views/customers/new.js.erb
alert ("Hello");

$("#customer_card").html("<%= j render "card" %>");
<% @customer = Customer.new # reset for new form %>
$(".edit_customer").replaceWith("<%= j render "form" %>");
$(".new_customer")[0].reset();

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<h3> Customers </h3>
<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Adress:</b>
  <%= @customer.adress %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

app/views/customers/show.js.erb
alert ("Show card");

$("#customer_card").html("<%= j render "show" %>");

app/views/customers/update.js.erb
$("#<%= dom_id @customer %>").replaceWith("<%= j render @customer %>");
<% @customer = Customer.new # reset for new form %>
$(".edit_customer").replaceWith("<%= j render "form" %>");
$(".new_customer")[0].reset();

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<div class = "menu">
  <ul>
    <li><a href="#">Home    </a></li>
    <li><a href="#">Customer</a></li>
    <li><a href="#">Product </a></li>
    <li><a href="#">Supplier</a></li>
    <li><a href="#">Setup   </a></li>
  </ul>
</div>

<h5>Listing lessons</h5>
<div class="tablearea">
<table>
  <tr class='list_line_odd'>
    <th>Title</th>
    <th>Description</th>
    <th>Image url</th>
    <th>Level</th>
    <th>More1</th>
    <th>More2</th>
    <th>More3</th>
  </tr>

<% @lessons.each do |lesson| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><%= link_to lesson.title, lesson.description.to_s%></td>
    <td><%= lesson.description %></td>
    <td><%= image_tag(lesson.image_url) %></td>
    <td><%= lesson.level %></td>
    <td><%= link_to 'Show', lesson.description.to_s %></td>
    <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
    <td><%= image_tag('b-order.gif') %></td>
  </tr>
<% end %>
</table>

</div>

app/views/lessons/new.html.erb
<h1>New lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @lesson.title %>
</p>

<p>
  <b>Description:</b>
  <%= @lesson.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @lesson.image_url %>
</p>

<p>
  <b>Level:</b>
  <%= @lesson.level %>
</p>


<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>